### ISSUE TITLE
Subscription field is required for professional registration

### ISSUE THREAD

**Issue by Kitdog** [wizzledonker/ezyassist#1]
Not too big of a deal, just noticed it while writing tests.
We probably don't need them to select one as it might cause confusion, could even just hide the fields and select free cruise by default if you don't want to mess with the forms too much

**Comment by winzlebee** [comment]
Hmm, had it hiding before. Must not be hiding again for some reason - will fix, thanks.

On 21 May 2019 18:27, Kitdog <notifications@github.com> wrote:

Not too big of a deal, just noticed it while writing tests.
We probably don't need them to select one as it might cause confusion, could even just hide the fields and select free cruise by default if you don't want to mess with the forms too much

**Comment by winzlebee** [comment]
Solved [commit](https://github.com/wizzledonker/ezyassist/commit/8dafbbcb755585eab67188a5c6ae92b05e79acbd)
